{% set name = "jill" %}
{% set version = "0.11.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jill-{{ version }}.tar.gz
  sha256: 0e2a3d02b8656b8fb5698f9acdc02204c855c68ad34b88dc0787ad8d349b6b51

build:
  entry_points:
    - jill=jill.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry-core
    - poetry
  run:
    - fire <0.6.0,>=0.5.0
    - jsonschema >=4.17.3
    - python >={{ python_min }}
    - python-gnupg >=0.5.0
    - requests >=2.28.2
    - requests-futures >=1.0.0
    - semantic_version >=2.10.0
    - python-wget >=3.2

test:
  imports:
    - jill
  commands:
    - pip check
    - jill --help
    - jill install nightly --confirm
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/johnnychen94/jill.py
  summary: JILL -- Julia Installer for Linux (MacOS, Windows and FreeBSD) -- Light
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mkitti
    - ngam
